version: '3.8'

services:
  dockerkali:
    image: dockerkali:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    #ports:
      #- '80:5000'    
    volumes:
      - ./data_volume:/data
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    stdin_open: true 
    tty: true
    #cap_add:
      #- NET_ADMIN
