version: '3.8'

services:
  dockerkali:
    image: dockerkali:latest
    build:
      context: .
      args:
        PENTESTUSERPASSWORD: $DOCKERKALIPENTESTPASSWORD
    environment:
      - DISPLAY=${DISPLAY}
    
    network_mode: host
    #ports:
      #- '80:5000'    
    volumes:
      - ./data_volume:/data
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - ./prefs.xml:/home/pentest/.java/.userPrefs/burp/prefs.xml
      - ./.BurpSuite:/home/pentest/.BurpSuite
    stdin_open: true 
    tty: true
    #cap_add:
      #- NET_ADMIN
